# Generates src/file_icons.rs and fonts/seti.ttf from the Seti UI icon theme.
#
#   pip install "fontTools==4.63.0"
#   python scripts/gen_seti_icons.py [path-to-fileIcons]
#
# Inputs are vendored in vendor/seti/ (seti.woff, setiIconMap.ts,
# seti-LICENSE.txt), so a clean checkout reproduces the committed outputs.
# setiIconMap.ts itself was generated by the Seti icon theme's published
# `seti-icon-theme.json` + `seti.woff` (the Helm fork's
# scripts/generate-seti-icons.mjs does the same).
# Seti UI is MIT licensed (c) 2014 Jesse Weed - see seti-LICENSE.txt.
#
# The outputs are committed, so a normal build never needs this script.

import re
import shutil
import sys
from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "vendor" / "seti"

ICON_ENTRY = re.compile(r'"((?:[^"\\]|\\.)*)"\s*:\s*\{\s*char:\s*"((?:[^"\\]|\\.)*)"\s*,\s*color:\s*"(#[0-9a-fA-F]{6})"')
CONST_ICON = re.compile(r'export const (SETI_[A-Z_]+): SetiIcon = \{\s*char:\s*"((?:[^"\\]|\\.)*)"\s*,\s*color:\s*"(#[0-9a-fA-F]{6})"')


def unescape(value: str) -> str:
    return re.sub(r"\\u([0-9a-fA-F]{4})", lambda m: chr(int(m.group(1), 16)), value)


def parse_map(text: str, start_marker: str, end_marker: str) -> list[tuple[str, str, str]]:
    body = text.split(start_marker, 1)[1].split(end_marker, 1)[0]
    return [(unescape(key), unescape(char), color) for key, char, color in ICON_ENTRY.findall(body)]


def rust_char(value: str) -> str:
    return f"'\\u{{{ord(value):x}}}'" if len(value) == 1 else "'\\u{fffd}'"


def rust_color(value: str) -> str:
    r, g, b = (int(value[i : i + 2], 16) for i in (1, 3, 5))
    return f"Color32::from_rgb(0x{r:02X}, 0x{g:02X}, 0x{b:02X})"


def rust_table(name: str, entries: list[tuple[str, str, str]]) -> str:
    lines = [f"pub static {name}: &[(&str, char, Color32)] = &["]
    for key, char, color in sorted(set(entries)):
        lines.append(f'    ("{key}", {rust_char(char)}, {rust_color(color)}),')
    lines.append("];")
    return "\n".join(lines)


def main() -> int:
    source = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SOURCE
    ts = (source / "setiIconMap.ts").read_text(encoding="utf-8")

    fonts = ROOT / "fonts"
    fonts.mkdir(exist_ok=True)
    font = TTFont(source / "seti.woff")
    font.flavor = None
    # fontTools stamps the head table with "now" on save; freeze it so the
    # committed font is byte-reproducible.
    font["head"].created = 0
    font["head"].modified = 0
    font.save(fonts / "seti.ttf", recalcTimestamp=False)
    shutil.copyfile(source / "seti-LICENSE.txt", fonts / "seti-LICENSE.txt")

    by_name = parse_map(ts, "setiIconByFileName", "setiIconByExtension")
    by_ext = parse_map(ts, "setiIconByExtension", "SETI_FONT_WOFF_BASE64")
    constants = dict((name, (unescape(char), color)) for name, char, color in CONST_ICON.findall(ts))
    default_file = constants.get("SETI_DEFAULT_FILE", ("\ue5ff", "#d4d7d6"))

    out = [
        "//! File-type icons from the Seti UI theme (MIT, (c) 2014 Jesse Weed).",
        "//! GENERATED by scripts/gen_seti_icons.py - do not edit by hand.",
        "",
        "use egui::Color32;",
        "",
        rust_table("BY_FILE_NAME", by_name),
        "",
        rust_table("BY_EXTENSION", by_ext),
        "",
        f"pub const DEFAULT_FILE: (char, Color32) = ({rust_char(default_file[0])}, {rust_color(default_file[1])});",
        "",
        "fn lookup(table: &[(&str, char, Color32)], key: &str) -> Option<(char, Color32)> {",
        "    table.binary_search_by(|(name, _, _)| name.cmp(&key)).ok().map(|index| (table[index].1, table[index].2))",
        "}",
        "",
        "/// Icon and colour of one file, by full name first, then by extension.",
        "pub fn for_file(name: &str) -> (char, Color32) {",
        "    let lower = name.to_ascii_lowercase();",
        "    let file_name = lower.rsplit(['/', '\\\\']).next().unwrap_or(&lower);",
        "    if let Some(icon) = lookup(BY_FILE_NAME, file_name) {",
        "        return icon;",
        "    }",
        "    let extension = file_name.rsplit_once('.').map(|(_, ext)| ext).unwrap_or(\"\");",
        "    if !extension.is_empty() && extension != file_name {",
        "        if let Some(icon) = lookup(BY_EXTENSION, extension) {",
        "            return icon;",
        "        }",
        "    }",
        "    DEFAULT_FILE",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        "    fn rust_and_docker_files_have_icons() {",
        "        let (rust, rust_color) = for_file(\"src/workspace.rs\");",
        "        assert_eq!(rust, for_file(\"main.rs\").0, \"extension lookup\");",
        "        assert_eq!(rust_color, for_file(\"a/b/other.rs\").1, \"same extension, same icon\");",
        "        let (docker, _) = for_file(\"Dockerfile\");",
        "        assert_ne!(docker, DEFAULT_FILE.0, \"by-name lookup\");",
        "        let (unknown, colour) = for_file(\"notes.unknownext\");",
        "        assert_eq!((unknown, colour), DEFAULT_FILE);",
        "    }",
        "",
        "    #[test]",
        "    fn tables_are_sorted_for_binary_search() {",
        "        assert!(BY_FILE_NAME.windows(2).all(|w| w[0].0 < w[1].0));",
        "        assert!(BY_EXTENSION.windows(2).all(|w| w[0].0 < w[1].0));",
        "    }",
        "}",
        "",
    ]
    (ROOT / "src" / "file_icons.rs").write_text("\n".join(out), encoding="utf-8")
    print(f"seti: {len(by_name)} file names, {len(by_ext)} extensions, font {fonts / 'seti.ttf'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
